version: "2"

services:

  web:
    build: .
    image: gqleung/xdebug
    restart: always
    ports:
      - "10086:80"
      - "3307:3306"
      - "2222:22"
    volumes:
      - "./files/html:/var/www/html"
      - "./ConfigurationFile/php/php.ini:/etc/php/7.2/apache2/php.ini"
